apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  # Add fields here
  replicas: 1
  applicationImage: openliberty/open-liberty:javaee8-ubi-min
  service:
    type: ClusterIP
    port: 9443
